import MyElement, { Point3D, Point3DCenter, createElement } from "./MyElement";
import { InfoTouch, noop, Offset } from "../utils/index";
import { CallbackEvent } from "../classes/Emitter";
declare type AngleType = "degress" | "radial";
export declare type AlignType = "left" | "center" | "right";
export declare type BaselineType = "top" | "middle" | "bottom";
declare type ColorType = "rgb" | "hsl" | "hue" | "hsb";
export declare type ParamsToRgb = [any?, any?, any?, number?];
declare type TextAlignType = AlignType | "start" | "end";
declare type TextBaselineType = BaselineType | "hanging" | "alphabetic" | "ideographic";
declare type RectMode = "corner" | "corners" | "center" | "radius";
declare type GlobalCompositeOperationType = "source-over" | "source-atop" | "source-in" | "source-out" | "destination-over" | "destination-atop" | "destination-in" | "destination-out" | "lighter" | "copy" | "xor";
declare type RuleClip = "nonzero" | "evenodd";
export declare type DirectionPattern = "repeat" | "repeat-x" | "repeat-y" | "no-repeat";
export default class fCanvas {
    static Element: typeof MyElement;
    static Point3D: typeof Point3D;
    static Point3DCenter: typeof Point3DCenter;
    private static _count;
    private readonly _id;
    private _el;
    private readonly _stamentReady;
    private readonly __store;
    constructor(width: number, height: number);
    constructor(element?: HTMLCanvasElement | string);
    constructor(element: HTMLCanvasElement | string, width?: number, height?: number);
    get $el(): HTMLCanvasElement;
    size(width: number, height: number): void;
    private _handlerEvent;
    private _handlerEventMousePress;
    private _cancelEventsSystem;
    private _restartEvents;
    touches: InfoTouch[];
    changedTouches: InfoTouch[];
    preventTouch(): void;
    stopTouch(): void;
    get mouseX(): number | null;
    get mouseY(): number | null;
    get movedX(): number;
    get movedY(): number;
    get pmouseX(): number;
    get pmouseY(): number;
    get mouseIsPressed(): boolean;
    get id(): number;
    private _createNewContext2d;
    blur(): void;
    noBlur(): void;
    desync(): void;
    noDesync(): void;
    useFloatPixel(): void;
    noFloatPixel(): void;
    _getPixel(value: number): number;
    get $context2d(): CanvasRenderingContext2D;
    append(parent?: HTMLElement): void;
    mount(element: HTMLCanvasElement | string): void;
    noClear(): void;
    get allowClear(): boolean;
    run(...elements: MyElement[]): void;
    get width(): number;
    set width(value: number);
    get height(): number;
    set height(value: number);
    get windowWidth(): number;
    get windowHeight(): number;
    save(): void;
    restore(): void;
    _toRadius(value: number): number;
    _toDegress(value: number): number;
    _toRgb([red, green, blue, alpha]: ParamsToRgb): any;
    _argsRect(x: number, y: number, width: number, height: number): [number, number, number, number];
    angleMode(): AngleType;
    angleMode(type: AngleType): void;
    colorMode(): ColorType;
    colorMode(mode: ColorType): void;
    rectMode(): RectMode;
    rectMode(mode: RectMode): void;
    fontSize(): number;
    fontSize(size: number): void;
    fontFamily(): string;
    fontFamily(font: string): void;
    fontWeight(): string;
    fontWeight(weight: string): void;
    clear(x?: number, y?: number, w?: number, h?: number): void;
    background(...params: ParamsToRgb): void;
    backgroundImage(image: CanvasImageSource): void;
    createImageData(height: ImageData): ImageData;
    createImageData(width: number, height: number): ImageData;
    getImageData(x: number, y: number, width: number, height: number): ImageData;
    putImageData(imageData: ImageData, x: number, y: number): void;
    putImageData(imageData: ImageData, x: number, y: number, xs: number, ys: number, width: number, height: number): void;
    createPattern(image: CanvasImageSource, direction: DirectionPattern): CanvasPattern | null;
    createRadialGradient(x1: number, y1: number, r1: number, x2: number, y2: number, r2: number): CanvasGradient;
    createLinearGradient(x: number, y: number, width: number, height: number): CanvasGradient;
    /**
     * @param {any} type="image/png"
     * @param {number} scale?
     * @return {string}
     */
    toDataURL(type?: string, scale?: number): string;
    rotate(): number;
    rotate(value: number): void;
    resetRotate(): void;
    resetTransform(): void;
    createElement: typeof createElement;
    preload(callback: noop): Promise<void>;
    setup(callback: noop): Promise<void>;
    draw(callback: noop): void;
    font(): string;
    font(font: string): void;
    textAlign(): TextAlignType;
    textAlign(type: TextAlignType): void;
    textBaseline(): TextBaselineType;
    textBaseline(middle: TextBaselineType): void;
    operation(): GlobalCompositeOperationType;
    operation(composite: GlobalCompositeOperationType): void;
    alpha(): number;
    alpha(alpha: number): void;
    resetAlpha(): void;
    translate(): Offset;
    translate(x: number, y: number): void;
    resetTranslate(): void;
    scale(): Offset;
    scale(x: number, y: number): void;
    resetScale(): void;
    clip(): void;
    clip(fillRule: RuleClip): void;
    clip(path: Path2D, fillRule: RuleClip): void;
    transform(matrix: DOMMatrix): void;
    transform(m11: number, m12: number, m21: number, m22: number, dx: number, dy: number): void;
    transform(): DOMMatrix;
    setTransform(matrix: DOMMatrix): void;
    setTransform(m11: number, m12: number, m21: number, m22: number, dx: number, dy: number): void;
    measureText(text: string): number;
    sin(angle: number): number;
    asin(sin: number): number;
    cos(angle: number): number;
    acos(cos: number): number;
    tan(angle: number): number;
    atan(tan: number): number;
    atan2(y: number, x: number): number;
    cursor(): void;
    noCursor(): void;
    _setIdFrame(id: number): void;
    loop(): void;
    noLoop(): void;
    get allowLoop(): boolean;
    on(name: string, callback: CallbackEvent): noop;
    off(resultEvent: noop): void;
    off(name: string, callback: CallbackEvent): void;
    mouseIn(callback: CallbackEvent): noop;
    mouseOut(callback: CallbackEvent): noop;
    touchStart(callback: CallbackEvent): noop;
    touchMove(callback: CallbackEvent): noop;
    touchEnd(callback: CallbackEvent): noop;
    mouseMove(callback: CallbackEvent): noop;
    mouseUp(callback: CallbackEvent): noop;
    mouseDown(callback: CallbackEvent): noop;
    mouseClicked(callback: CallbackEvent): noop;
}
export declare const noopFCanvas: fCanvas;
export {};
