import { noop, Offset } from "../utils/index";
import fCanvas, { DirectionPattern } from "./fCanvas";
import Peers from "../classes/Peers";
declare type LineJoin = "bevel" | "round" | "miter";
declare type LineCap = "butt" | "round" | "square";
export default abstract class MyElement {
    private static _count;
    get type(): "rect" | "circle" | "point" | "unknown";
    private readonly _id;
    get id(): number;
    private readonly _els;
    private _idActiveNow;
    private readonly _queue;
    private __addEl;
    constructor(canvas?: fCanvas);
    _run(canvas: fCanvas, peers?: Peers): void;
    add(...elements: MyElement[]): void;
    run(element: MyElement): void;
    get $parent(): fCanvas;
    get $context2d(): CanvasRenderingContext2D;
    sin(angle: number): number;
    asin(sin: number): number;
    cos(angle: number): number;
    acos(cos: number): number;
    tan(angle: number): number;
    atan(tan: number): number;
    atan2(y: number, x: number): number;
    get mouseX(): number | null;
    get mouseY(): number | null;
    get movedX(): number;
    get movedY(): number;
    get pmouseX(): number;
    get pmouseY(): number;
    get mouseIsPressed(): boolean;
    get windowWidth(): number;
    get windowHeight(): number;
    fill(hue: number, saturation: number, lightness: number, alpha?: number): this;
    fill(red: number, green: number, blue: number, alpha?: number): this;
    fill(color?: string | CanvasGradient | CanvasImageSource | number): this;
    stroke(hue: number, saturation: number, lightness: number, alpha?: number): this;
    stroke(red: number, green: number, blue: number, alpha?: number): this;
    stroke(color?: string | CanvasGradient | CanvasImageSource | number): this;
    noFill(): this;
    lineWidth(): number;
    lineWidth(width: number): this;
    miterLimit(): number;
    miterLimit(value: number): this;
    shadowOffset(): Offset;
    shadowOffset(x: number, y: number): this;
    measureText(text: string): number;
    begin(): this;
    close(): this;
    save(): this;
    restore(): this;
    rotate(): number;
    rotate(angle: number): this;
    translate(): Offset;
    translate(x: number, y: number): this;
    arc(x: number, y: number, radius: number, astart: number, astop: number, reverse?: boolean): this;
    pie(x: number, y: number, radius: number, astart: number, astop: number, reverse?: boolean): this;
    line(x1: number, y1: number, x2: number, y2: number): this;
    ellipse(x: number, y: number, radius1: number, radius2: number, astart: number, astop: number, reverse: number): this;
    circle(x: number, y: number, radius: number): this;
    point(x: number, y: number): this;
    triangle(x1: number, y1: number, x2: number, y2: number, x3: number, y3: number): this;
    drawImage(image: CanvasImageSource, x: number, y: number): this;
    drawImage(image: CanvasImageSource, x: number, y: number, width: number, height: number): this;
    drawImage(image: CanvasImageSource, sx: number, sy: number, swidth: number, sheight: number, x: number, y: number, width: number, height: number): this;
    rRect(x: number, y: number, width: number, height: number, radius: string | number): this;
    rRect(x: number, y: number, width: number, height: number, radiusLeft: string | number, radiusRight: string | number): this;
    rRect(x: number, y: number, width: number, height: number, radiusTopLeft: string | number, radiusTopRight: string | number, radiusBottomRight: string | number, radiusBottomLeft: string | number): this;
    rect(x: number, y: number, width: number, height: number): this;
    quadratic(cpx: number, cpy: number, x: number, y: number): this;
    bezier(cp1x: number, cp1y: number, cp2x: number, cp2y: number, x: number, y: number): this;
    move(x: number, y: number): this;
    to(x: number, y: number): this;
    fillText(text: string, x: number, y: number, maxWidth?: number): this;
    strokeText(text: string, x: number, y: number, maxWidth?: number): this;
    fillRect(x: number, y: number, width: number, height: number): this;
    strokeRect(x: number, y: number, width: number, height: number): this;
    lineDashOffset(): number;
    lineDashOffset(value: number): this;
    lineDash(): number[];
    lineDash(segments: number[]): this;
    lineDash(...segments: number[]): this;
    arcTo(x1: number, y1: number, x2: number, y2: number, radius: number): this;
    isPoint(x: number, y: number): boolean;
    createImageData(height: ImageData): ImageData;
    createImageData(width: number, height: number): ImageData;
    getImageData(x: number, y: number, width: number, height: number): ImageData;
    putImageData(imageData: ImageData, x: number, y: number): this;
    putImageData(imageData: ImageData, x: number, y: number, xs: number, ys: number, width: number, height: number): this;
    createPattern(image: CanvasImageSource, direction: DirectionPattern): CanvasPattern | null;
    createRadialGradient(x1: number, y1: number, r1: number, x2: number, y2: number, r2: number): CanvasGradient;
    createLinearGradient(x: number, y: number, width: number, height: number): CanvasGradient;
    lineJoin(): LineJoin;
    lineJoin(type: LineJoin): this;
    lineCap(): LineCap;
    lineCap(value: LineCap): this;
    shadowBlur(): number;
    shadowBlur(opacity: number): this;
    shadowColor(hue: number, saturation: number, lightness: number, alpha?: number): this;
    shadowColor(red: number, green: number, blue: number, alpha?: number): this;
    shadowColor(color?: string | CanvasGradient | CanvasImageSource | number): this;
    drawFocusIfNeeded(element: Element): this;
    drawFocusIfNeeded(path: Path2D, element: Element): this;
    polyline(...points: number[]): this;
    polyline(...points: [number, number][]): this;
    polygon(...points: number[]): this;
    polygon(...points: [number, number][]): this;
    drawing(program: noop): void;
    backup(program: noop): void;
}
export declare class Point3D extends MyElement {
    x: number;
    y: number;
    z: number;
    constructor(x?: number, y?: number, z?: number);
    rotateX(angle: number): void;
    rotateY(angle: number): void;
    rotateZ(angle: number): void;
}
export declare class Point3DCenter extends MyElement {
    private static persistent;
    private __x;
    private __y;
    private __z;
    constructor(x: number, y: number, z?: number);
    get scale(): number;
    get x(): number;
    set x(value: number);
    get y(): number;
    set y(value: number);
    get z(): number;
    set z(value: number);
    get(value: number): number;
    get(prop: string): number;
}
export declare function createElement(callback: {
    (canvas: MyElement): void;
}): MyElement;
export {};
